/**
 * AUTO-GENERATED by `facet icons generate` - DO NOT EDIT BY HAND.
 *
 * The exact lucide icon subset this app uses (81 icons
 * resolved against lucide-react v1.31.0), plus the default
 * semantic set. Importing from here instead of the full lucide map keeps
 * the bundle tree-shaken: only these icons ship, which avoids pulling the
 * ~1700-icon map (and the memory/heap cost that comes with it).
 *
 * Regenerate when you add or remove icons:
 *   npx facet icons generate
 */

import type { SVGProps } from "react";
import {
  ArrowLeft,
  ArrowRight,
  Bell,
  BookOpen,
  Boxes,
  Brain,
  Building,
  Calendar,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleQuestionMark,
  CircleX,
  ClipboardCheck,
  ClipboardList,
  Compass,
  Copy,
  CreditCard,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FaceSlightlySmiling,
  FlaskConical,
  FileText,
  FingerprintPattern,
  Globe,
  GraduationCap,
  HeartHandshake,
  Info,
  KeyRound,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutPanelLeft,
  Lightbulb,
  List,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  Minus,
  Menu,
  MessageCircle,
  MessageSquare,
  Moon,
  Palette,
  PanelLeft,
  Printer,
  Puzzle,
  QrCode,
  RotateCcw,
  Ruler,
  Scale,
  School,
  ScrollText,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Star,
  Store,
  Sun,
  Target,
  Terminal,
  Trash,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Upload,
  User,
  UserPlus,
  Users,
  X,
  Zap,
} from "@arcevo/facet-components/icons";
import type { LucideIcon } from "@arcevo/facet-components/icons";

const ICONS: Record<string, LucideIcon> = {
  "settings": Settings,
  "search": Search,
  "check": Check,
  "x": X,
  "menu": Menu,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevrons-up-down": ChevronsUpDown,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "moon": Moon,
  "sun": Sun,
  "bell": Bell,
  "user": User,
  "users": Users,
  "sparkles": Sparkles,
  "book-open": BookOpen,
  "copy": Copy,
  "trash": Trash,
  "building": Building,
  "list": List,
  "layout-grid": LayoutGrid,
  "file-text": FileText,
  "triangle-alert": TriangleAlert,
  "mail": Mail,
  "message-square": MessageSquare,
  "message-circle": MessageCircle,
  "zap": Zap,
  "palette": Palette,
  "layout-dashboard": LayoutDashboard,
  "circle-question-mark": CircleQuestionMark,
  "credit-card": CreditCard,
  "log-out": LogOut,
  "upload": Upload,
  "qr-code": QrCode,
  "panel-left": PanelLeft,
  "layout-panel-left": LayoutPanelLeft,
  "compass": Compass,
  "layers": Layers,
  "key-round": KeyRound,
  "boxes": Boxes,
  "shield-check": ShieldCheck,
  "terminal": Terminal,
  "puzzle": Puzzle,
  "lock": Lock,
  "ruler": Ruler,
  "fingerprint-pattern": FingerprintPattern,
  "store": Store,
  "globe": Globe,
  "external-link": ExternalLink,
  "brain": Brain,
  "calendar": Calendar,
  "chart-column": ChartColumn,
  "circle": Circle,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-x": CircleX,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  "dashboard": LayoutDashboard,
  "document": FileText,
  "download": Download,
  "eye": Eye,
  "eye-off": EyeOff,
  "face-slightly-smiling": FaceSlightlySmiling,
  "graduation-cap": GraduationCap,
  "heart-handshake": HeartHandshake,
  "info": Info,
  "lightbulb": Lightbulb,
  "loader-circle": LoaderCircle,
  "logout": LogOut,
  "printer": Printer,
  "rotate-ccw": RotateCcw,
  "scale": Scale,
  "school": School,
  "scroll-text": ScrollText,
  "star": Star,
  "target": Target,
  "trophy": Trophy,
  "user-plus": UserPlus,
  "flask-conical": FlaskConical,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "minus": Minus,
};

export type IconName = keyof typeof ICONS;

export interface GeneratedIconProps extends SVGProps<SVGSVGElement> {
  name: string;
  className?: string;
  size?: number | string;
}

/** Renders a used icon by name. Unknown names render nothing. */
export function GeneratedIcon({ name, className, size, ...props }: GeneratedIconProps) {
  const kebab = name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
  const Component = ICONS[kebab] ?? ICONS[name];
  if (!Component) return null;
  return <Component className={className} size={size} {...props} />;
}

export default GeneratedIcon;
